project:
  type: website
  output-dir: docs

website:
  title: "nusestherkho.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - NM2207 Weekly Journal.qmd
      - Photography.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
 

editor: visual

